#!/usr/bin/env python
"""Embed the JavaScript msgpack runtime into a Python module.

`msgspec.javascript.codec` inlines a dependency-free copy of the msgpack
reader/writer into every codec it generates. The runtime is authored (and
node-tested) at ``javascript/src/msgpack.mjs``; this script converts it into the
importable ``src/msgspec/_msgpack_runtime_js.py`` by stripping the ESM
``export`` keywords. Run it whenever the ``.mjs`` changes; ``test_javascript.py``
asserts the two stay in sync.
"""

from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
MJS = ROOT / "javascript" / "src" / "msgpack.mjs"
OUT_JS = ROOT / "src" / "msgspec" / "_msgpack_runtime_js.py"
OUT_TS = ROOT / "src" / "msgspec" / "_msgpack_runtime_ts.py"


def inline(mjs_source: str) -> str:
    """The runtime as it is inlined into a generated module (no ESM exports)."""
    return mjs_source.replace("export class ", "class ").replace(
        "export function ", "function "
    )


# TypeScript param-type annotations, keyed on the exact JS method/function
# definition line. Class fields are declared separately below.
_TS_PARAMS = {
    "_ensure(k) {": "_ensure(k: number) {",
    "u8(x) {": "u8(x: number) {",
    "raw(u) {": "raw(u: Uint8Array) {",
    "bool(x) {": "bool(x: boolean) {",  # Writer.bool (Reader.bool has no arg)
    "int(x) {": "int(x: number) {",
    "int64(x) {": "int64(x: bigint) {",
    "float(x) {": "float(x: number) {",
    "float32(x) {": "float32(x: number) {",
    "str(s) {": "str(s: string) {",
    "bin(u) {": "bin(u: Uint8Array) {",
    "arrayHeader(n) {": "arrayHeader(n: number) {",
    "mapHeader(n) {": "mapHeader(n: number) {",
    "ext(code, u) {": "ext(code: number, u: Uint8Array) {",
    "value(x) {": "value(x: any) {",  # Writer.value (Reader.value has no arg)
    "constructor(bytes) {": "constructor(bytes: Uint8Array) {",
    "function b64encode(u8) {": "function b64encode(u8: Uint8Array) {",
    "function b64decode(str) {": "function b64decode(str: string) {",
    "function encHexInt(v, signed, force) {": (
        "function encHexInt(v: bigint, signed: boolean, force: boolean) {"
    ),
    "function decHexInt(x) {": "function decHexInt(x: any) {",
    "function decArray(r, fn) {": (
        "function decArray(r: Reader, fn: (r: Reader) => any) {"
    ),
    "function decSet(r, fn) {": "function decSet(r: Reader, fn: (r: Reader) => any) {",
    "function decMap(r, kfn, vfn) {": (
        "function decMap(r: Reader, kfn: (r: Reader) => any, vfn: (r: Reader) => any) {"
    ),
}

# Class fields (inferred from the constructors), inserted after each class header.
_TS_FIELDS = {
    "class Writer {\n": "class Writer {\n  b: Uint8Array;\n  dv: DataView;\n  n: number;\n",
    "class Reader {\n": "class Reader {\n  b: Uint8Array;\n  dv: DataView;\n  p: number;\n",
}


# Miscellaneous type annotations for locals TS can't infer under `strict`.
_TS_EXTRA = {
    "let _B64R = null;": "let _B64R: Record<string, number> | null = null;",
    "const o = {};": "const o: any = {};",
}


def to_typescript(inlined: str) -> str:
    """Turn the inlined JS runtime into type-annotated TypeScript."""
    ts = inlined
    for js, tsig in _TS_PARAMS.items():
        ts = ts.replace(js, tsig)
    for header, replacement in _TS_FIELDS.items():
        ts = ts.replace(header, replacement)
    for js, tsig in _TS_EXTRA.items():
        ts = ts.replace(js, tsig)
    return ts


def render(name: str, body: str) -> str:
    assert "'''" not in body and "\\" not in body  # safe to embed as a raw block
    return (
        f"# Generated by scripts/gen_js_runtime.py from javascript/src/msgpack.mjs\n"
        f"# Do not edit by hand - edit the .mjs and re-run the generator.\n"
        f'{name} = r"""\n' + body + '"""\n'
    )


if __name__ == "__main__":
    inlined = inline(MJS.read_text())
    OUT_JS.write_text(render("RUNTIME", inlined))
    OUT_TS.write_text(render("RUNTIME", to_typescript(inlined)))
    print(f"wrote {OUT_JS.relative_to(ROOT)} and {OUT_TS.relative_to(ROOT)}")
